/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package coit13229.assessment1.server;

import java.util.HashMap;
import java.util.Map;
import javax.swing.Box;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import model.Drone;
import model.Fire;

/**
 *
 * @author thainguyen
 */
public class ServerGUI extends javax.swing.JFrame {

    /**
     * Creates new form ServerGUI
     */
    public ServerGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deleteFireReportButton = new javax.swing.JButton();
        moveDroneButton = new javax.swing.JButton();
        shotDownServerButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        messagesTextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        recallDroneButton = new javax.swing.JButton();
        mapPane = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        deleteFireReportButton.setText("Delete Fire Report");
        deleteFireReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteFireReportActionPerformed(evt);
            }
        });

        moveDroneButton.setText("Move Drone");
        moveDroneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveDroneActionPerformed(evt);
            }
        });

        shotDownServerButton.setText("Shot Down Server");
        shotDownServerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shotDownServerActionPerformed(evt);
            }
        });

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Messages", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 18))); // NOI18N

        messagesTextArea.setEditable(false);
        messagesTextArea.setBackground(new java.awt.Color(255, 255, 255));
        messagesTextArea.setColumns(20);
        messagesTextArea.setRows(5);
        jScrollPane2.setViewportView(messagesTextArea);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setText("Intelligent Bushfire Detection and Management System");

        jButton5.setText("Clear Messages");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearMessagesActionPerform(evt);
            }
        });

        recallDroneButton.setText("Recall Drone");
        recallDroneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recallDroneActionPerformed(evt);
            }
        });

        mapPane.setBackground(new java.awt.Color(255, 255, 255));
        mapPane.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Map", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 18))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coit13229/assessment1/server/resources/map.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mapPane.add(jLabel2);
        jLabel2.setBounds(5, 25, 1272, 796);
        jLabel2.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(deleteFireReportButton)
                        .addGap(18, 18, 18)
                        .addComponent(moveDroneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(recallDroneButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(shotDownServerButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton5)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mapPane, javax.swing.GroupLayout.PREFERRED_SIZE, 872, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteFireReportButton)
                    .addComponent(moveDroneButton)
                    .addComponent(shotDownServerButton)
                    .addComponent(recallDroneButton))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mapPane, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteFireReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteFireReportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteFireReportActionPerformed

    private void moveDroneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveDroneActionPerformed
        JTextField xField = new JTextField(5);
        JTextField yField = new JTextField(5);
        JComboBox droneBox = new JComboBox(drones.keySet().toArray());

        JPanel myPanel = new JPanel();
        myPanel.add(droneBox);
        myPanel.add(new JLabel("new x:"));
        myPanel.add(xField);
        myPanel.add(Box.createHorizontalStrut(15)); // a spacer
        myPanel.add(new JLabel("new y:"));
        myPanel.add(yField);

        int result = JOptionPane.showConfirmDialog(null, myPanel,
                "Move drone to new location", JOptionPane.OK_CANCEL_OPTION);
        if (result == JOptionPane.OK_OPTION) {
            int newX = Integer.parseInt(xField.getText());
            int newY = Integer.parseInt(yField.getText());
            int droneId = Integer.parseInt(droneBox.getSelectedItem().toString());
            server.moveDrone(droneId,newX, newY);
        }
        
    }//GEN-LAST:event_moveDroneActionPerformed

    private void shotDownServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shotDownServerActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_shotDownServerActionPerformed

    private void clearMessagesActionPerform(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearMessagesActionPerform
        // TODO add your handling code here:
        messagesTextArea.setText("");
    }//GEN-LAST:event_clearMessagesActionPerform

    private void recallDroneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recallDroneActionPerformed
        JOptionPane.showMessageDialog(this, "Recalling drones");
        server.recallDrones();
    }//GEN-LAST:event_recallDroneActionPerformed

    public void addDroneToMap(Drone drone) {
        JLabel droneIcon = new JLabel();
        drones.put(drone.getId(), droneIcon);
        droneIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coit13229/assessment1/server/resources/drone.png")));
        droneIcon.setBounds(drone.getX(), drone.getY(), 64, 64);
        mapPane.add(droneIcon, 0);
        mapPane.validate();
    }

    public void addFireToMap(Fire fire) {
        JLabel fireIcon = new JLabel();
        fires.put(fire.getId(), fireIcon);
        fireIcon.setText(String.valueOf(fire.getServerity()));
        fireIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coit13229/assessment1/server/resources/fire.png")));
        fireIcon.setBounds(fire.getX(), fire.getY(), 64, 64);
        mapPane.add(fireIcon, Integer.valueOf(1));
        mapPane.validate();
    }

    public void moveDrone(Drone drone) {
//        droneIcon.setBounds(drone.getX(), drone.getY(), 64, 64);
        JLabel droneIcon = drones.get(drone.getId());
        droneIcon.setLocation(drone.getX(), drone.getY());
        mapPane.validate();
    }

    public void generateMessage(String message) {
        messagesTextArea.append(message);
    }

    public void setServer(Server server) {
        this.server = server;
    }

    /**
     * @param args the command line arguments
     */
    Server server;
    Map<Integer, JLabel> fires = new HashMap();
    Map<Integer, JLabel> drones = new HashMap();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteFireReportButton;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLayeredPane mapPane;
    private javax.swing.JTextArea messagesTextArea;
    private javax.swing.JButton moveDroneButton;
    private javax.swing.JButton recallDroneButton;
    private javax.swing.JButton shotDownServerButton;
    // End of variables declaration//GEN-END:variables
}
